config/routes.rb
Rails.application.routes.draw do
  devise_for :companies

  get 'stories' => 'stories#index'
  get 'stories/new'  =>  'stories#new' #ストーリー投稿画面
  post 'tweets'      =>  'tweets#create' #ストーリー投稿機能

  root 'stories#index'

  
  
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController

  def index
  end

  def new
  end

  def create
    Story.create(name: params[:name], image: params[:image], text: params[:text])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Prtable
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/stories/_footer.html.haml
.footer
  .f-nav
    %ul
      %li1 新着一覧
      %li2　トピック一覧
      %li3　ストーリー掲載企業一覧
    %ul
      %li4 よくある質問
      %li5　PR Tableについて 
      %li6　利用規約
      %li7 プライバシーポ゚リシー
      %li8 運営会社
      %li9 お問い合わせ
      %li10 PR Table Labo
  .social-icon
    %ul
      %li11 
        %i.fa.fa-facebook
      %li12
        %i.fa.fa-twitter
      %li13
        %i.fa.fa-rss

app/views/stories/_header.html.haml
.global-header
  .logo
    = image_tag("https://www.pr-table.com/assets/logo.svg")
  .g-nav
    %ul
      %li 新着一覧
      %li　PRTABLEとは?
  .buttons
    .create
      = link_to "ストーリーを作成", stories_new_path, method: :get
    .login 
      = link_to "ログイン/新規登録", new_company_session_path, method: :get
    %i.fa.fa-search

app/views/stories/_leftcont.html.haml
.stories
  .stories-article  
    %a
      .story-image
        = image_tag("https://www.pr-table.com/upimgs/story_images/3246/large/ee727c078123a36fa58f6e997effc039df4127f4.jpg?1496739397")
    %strong 働き方のスタンダードはこう作られる。“やらない”を徹底したカオナビのビジネス戦略
    %p 株式会社カオナビ
  .stories-article
    %a
      .story-image
        = image_tag("https://www.pr-table.com/upimgs/story_images/3231/large/ad4e3976e7619c5414ddafa97466d37f5c06208e.jpg?1496478482")
    %strong デジタル時代の“次なる一手”、トランスコスモスが独自に開発するDECサービスとは？
    %p トランスコスモス株式会社
  .stories-article
    %a
      .story-image
        = image_tag("https://www.pr-table.com/upimgs/story_images/3144/large/dd386fa222ce18c80c7e4e8191803f9c88bfdd0e.jpg?1495155867")
    %strong 決済業務を委託し顧客数が200%成長！ 飲食店向け鮮魚仕入れサービス「魚ポチ」の急成長
    %p 株式会社ネットプロテクションズ
  .stories-article
    %a
      .story-image
        = image_tag("https://www.pr-table.com/upimgs/story_images/3203/large/be2a8692e7ce51d36f576d2cf1348d53db4d7952.png?1496296100")
    %strong 中小・ベンチャー企業とともに成長する喜びこそが原動力——ソウルドアウトはいかにして生まれたか
    %p ソウルドアウト株式会社
  .stories-article
    %a
      .story-image
        = image_tag("https://www.pr-table.com/upimgs/story_images/3213/large/d134f61e7bddcc60fcbc4c54e52beee9ddc80047.jpg?1496321609")
    %strong 「世の中に、自分らしく生きる人を増やしたい」BOLBOP創業ストーリー
    %p 株式会社BOLBOP
  .stories-article
    %a
      .story-image
        = image_tag("https://www.pr-table.com/upimgs/story_images/3222/large/dab1c5627cce3fcd44617b05d18af05055729b2b.JPG?1496392483")
    %strong シリコンバレーやアジアからの参加からも！ Onlabは世界の起業家とともに未来を創る
    %p　Open Network Lab
  .stories-article
    %a
      .story-image
        = image_tag("https://www.pr-table.com/upimgs/story_images/2941/large/ff7885d2e047a4c951ccc90a19f3e402a67c840a.JPG?1492131197")
    %strong お店づくりのプロ「ストア・エキスプレス」が、顧客満足度を向上させられた理由
    %p 株式会社ネットプロテクションズ
  .stories-article
    %a
      .story-image
        = image_tag("https://www.pr-table.com/upimgs/story_images/3188/large/c2288ee7dc6b49361f63fbc0289999ea8549529b.jpg?1496132909")
    %strong 48時間1本勝負の“弾丸トラベル採用”！——台湾人採用に乗り出す日系企業に迫る
    %p 株式会社ネオキャリア
  .stories-article
    %a
      .story-image
        = image_tag("https://www.pr-table.com/upimgs/story_images/3196/large/0c04ec9a2c53b89c306e3bc84d57935c329171eb.jpg?1496189199")
    %strong 仕事もプライベートも、お金では買えない幸せを求めて――「PERSOL」で働く社員の“本音”
    %p PERSOLグループ
  .stories-article
    %a
      .story-image
        = image_tag("https://www.pr-table.com/upimgs/story_images/3139/large/f4216c0f27f72df09db1e5e0364fe26d5e89fab5.jpg?1495009037")
    %strong　育児と仕事の両立のために。あえて選んだマネージャーの道
    %p エン・ジャパン株式会社
  .stories-article
    %a
      .story-image
        = image_tag("https://www.pr-table.com/upimgs/story_images/3156/large/b8870752be3d3ab60fa10f073b876fb7fc6e3753.jpg?1495413567")
    %strong 「言葉と映像」を研ぎ澄ますーー新世代CMプランナーが考えるコミュニケーションの根幹
    %p 電通報
  .stories-article
    %a
      .story-image
        = image_tag("https://www.pr-table.com/upimgs/story_images/3187/large/a65674809324e1b641752bdf756b7f6e7a75aac2.png?1495975113")
    %strong おいしいだけじゃないーーウェブコンサル企業が導入した“食”にまつわる取り組みとは
    %p 株式会社ペンシル
  .stories-article
    %a
      .story-image
        = image_tag("https://www.pr-table.com/upimgs/story_images/3181/large/d938f67abf1779dcf24d63d6b490ef665d20d9a3.JPG?1495699480")
    %strong “日本一のお花見”が楽しめる場所は北海道にある───桜と共に歴史を重ねる、松前町のあゆみ
    %p 松前町
  .stories-article
    %a
      .story-image
        = image_tag("https://www.pr-table.com/upimgs/story_images/3179/large/8c9dcb93bdb2f0656710b80f1de7c65419d6fbe1.jpg?1495685947")
    %strong 会社員にこそ、「新しい働き方」を叶えてほしい―――三井不動産の新たな挑戦
    %p 三井不動産株式会社
  .stories-article
    %a
      .story-image
        = image_tag("https://www.pr-table.com/upimgs/story_images/3162/large/d5c33c7efaf6207fbda4bced57d9866a242470a1.JPG?1495528484")
    %strong 入社1年目で海外拠点立ち上げに抜擢ーー企業に属さないはずだった彼を駆り立てた挑戦心
    %p 株式会社ベネフィット・ワン
.more
  %aa 
    %i.fa.fa-chevron-circle-right
      新着ストーリー一覧

app/views/stories/_pickups.html.haml
.pickup-2stories
  .story1
    = image_tag("https://www.pr-table.com/upimgs/story_images/3238/large/d06db80f88db01b294fd2759ef368b3458725d9b.jpg?1496725560")
    .title
      %titlefigure
        .company-img
          = image_tag("https://www.pr-table.com/upimgs/profile_images/837/medium/62c4227a6bb759189299b61730c2737339e6bf94.png?1495672896")
        %titlefigucuption 竜宮株式会社
        %titlestrong　時代の変化、幾度の事業転換……それでも70年の歴史と技術が“夢の寝具”を完成させた
  .story2
    = image_tag("https://www.pr-table.com/upimgs/story_images/3109/large/945dfe1db25c33b42f16a8496ecc8b6f00e15202.jpg?1494579036")
    .title
      %titlefigure
        .company-img
          = image_tag("https://www.pr-table.com/upimgs/profile_images/16/medium/51456a632555c2aeb7452560e9017d17c0b7d754.jpg?1442547187")
        %titlefigucuption Sansan株式会社
        %titlestrong　“Sansan Innovation Project 2017”——Sansanが伝えた「働き方進化論」  

app/views/stories/_sidecont.html.haml
.side-stories
  %h2 注目ストーリー
  .side-wrap
    %article
      .side-story-image
        = image_tag("https://www.pr-table.com/upimgs/story_images/1890/large/d527383b6e118ca7a377701e9312f6dd297e8210.jpg?1479378451")
      .story-info
        %h4 日本の起業家が世界へ羽ばたく支援をーーOpen Network Lab創設者の想い
        %h5 ㈱carity
    %article
      .side-story-image
        = image_tag("https://www.pr-table.com/upimgs/profile_images/676/medium/34ba914c2f32e561c9567b4089d1f77dd62bfebb.jpg?1487317905")
      .story-info
        %h4 留学といえばTHE RYUGAKU！曖昧ワードで検索する、あなたに届けたい記事
        %h5 アブログ合同会社
    %article 
      .side-story-image
        = image_tag("https://www.pr-table.com/upimgs/profile_images/237/medium/75c4cff6d373a2e973cf86b37080bc4932fc1f4a.gif?1458117841")
      .story-info
        %h4 教育を通して、介護職員が喜んで働けるようになる仕掛け
        %h5 ユアブライト株式会社
.side-tags
  %h6　おすすめトピック
  .under-side-wrap
    %ul
      %li　士業
      %li　周年記念
      %li　元クックパッド   
      %li　創業秘話
      %li　東京五輪2020
      %li　IPO 
      %li　ユーザー事例
      %li　ピッチイベント
      %li　IoT
      %li　研究開発
      %li　オフィス
      %li　兄弟
      %li　東大卒ベンチャー  
      %li　CSR・社会貢献活動
      %li　キャリア
      %li　ベンチャー
  .side-more 
    %h7 <　トピック一覧
.side-companylist
  %h8 ストーリー掲載企業
  .story-side-wrap
    %h9
      .img
        = image_tag("https://www.pr-table.com/upimgs/profile_images/615/medium/07091e85425d32453291e81114b0cd2d6790a5c2.jpeg?1484300684")
      %figcaption Open Network Lab
    %h9
      .img
        = image_tag("https://www.pr-table.com/upimgs/profile_images/224/medium/3bf36ec8333fdbf7b82d9b281b9dd7f0997d9c04.jpeg?1456289251")
      %figcaption  株式会社リクルートキャリア
    %h9
      .img
        = image_tag("https://www.pr-table.com/upimgs/profile_images/14/medium/ddb0ab26b00828a372b7c1dfc760628c5f64858d.png?1442299254")
      %figcaption コトバンク
    %h9
      .img
        = image_tag("https://www.pr-table.com/upimgs/profile_images/260/medium/59f9fc8c6da8fa528e288327258d12d8b745a6e7.PNG?1461058454")
      %figcaption 株式会社アールナイン
    %h9
      .img
        = image_tag("https://www.pr-table.com/upimgs/profile_images/177/medium/27bf8ef793138166b3c2fa892708ab330e93102f.png?1453690727")
      %figcaption 株式会社BEC
  .side-more 
    %h7 <　ストーリー掲載企業一覧
.side-banner
  = image_tag("https://www.pr-table.com/assets/side_banner.gif")

app/views/stories/create.html.haml
.contents.row
  .success
    %h3
      投稿が完了しました。
    %a.btn{:href => "/tweets"} 投稿一覧へ戻る

app/views/stories/index.html.haml
.body
  .header
    = render partial: 'header'
  .p-stories
    = render partial: 'pickups'
  .container
    .left-contents
      = render partial: 'leftcont'
    .side-contents
      = render partial: 'sidecont'
  .footer-wrapper
    = render partial: 'footer'
  

app/views/stories/new.html.haml
.body
  .header
    = render partial: 'header'
  .breadcrumbs

  .container-new
    .contents-new
      .story-new
        .author
        .h1 Sansan Innovation Project 2017”——Sansanが伝えた「働き方進化論」
        .intro Sansan株式会社は、2017年2月2日、プライベートカンファレンス「Sansan Innovation Project 2017 働き方進化論」を東京で開催しました。昨年に続き2回目の開催となった今年は、約4,200名の方々にご参加いただきました。この日、当社は何を伝えたのか――その背景とメッセージをご紹介します。
        .socials
        .topics
          .h2 SansanProjectとは
          .img
          .topics-body
        .topics
          .h2
          .img
          .topics-body
        .topics
          .h2
          .img
          .topics-body
        .topics
          .h2
          .img
          .topics-body
        .story-footer
        .relative-story
        .notice-story

  .footer-wrapper